// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biozvoilewjikgjwaocf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpb3p2b2lsZXdqaWtnandhb2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzk3MjgsImV4cCI6MjA2ODk1NTcyOH0.kgoTPpgE5zshntQNmL0WM4Uy7JC8AM82XcgkzttUOMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});